version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db_share:/db_share
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - type: volume
        source: bundle
        target: /usr/local/bundle
      - type: volume
        source: node-modules
        target: /app/node_modules
        volume:
          nocopy: true
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    stdin_open: true
    tty: true
volumes:
  bundle:
  db-volume:
  node-modules:
